brew "fzf"
brew "git"
brew "jq"
brew "kind"
brew "mdcat"
brew "ncdu"
brew "the_silver_searcher"
brew "thefuck"
brew "tree"
brew "watch"
brew "wget"
brew "zsh-syntax-highlighting"

brew "go"
brew "chruby"
brew "ruby-install"
brew "python", link: true, overwrite: true

cask "caffeine"
cask "discord"
cask "docker"
cask "flycut"
cask "google-chrome"
cask "iterm2"
cask "keepassxc"
cask "mutespotifyads"
cask "slack"
cask "spectacle"
cask "spotify"
cask "visual-studio-code"
cask "vlc"
cask "zoom"
